using System.Text.Json;
using FluentValidation;
using LRW.Core.Configuration;
using LRW.Core.Helpers;

namespace LRW.UnitTests.Core;

public class HelpersTests
{
    #region JsonHelper

    [Fact]
    public void Serialize_ReturnSnakeCaseJsonString()
    {
        //Arrange
        var obj = new
        {
            TestA = "Test",
            TestB = 2,
            TestC = 0.8,
            TestD = true,
            TestE = new { TestA = "Test" },
            TestF = new[] { "A", "B" }
        };

        const string expected =
            "{\"test_a\":\"Test\",\"test_b\":2,\"test_c\":0.8,\"test_d\":true,\"test_e\":{\"test_a\":\"Test\"},\"test_f\":[\"A\",\"B\"]}";

        //Act
        var result = JsonHelper.Serialize(obj);

        //Assert
        Assert.Equal(expected, result);
    }

    [Fact]
    public void Deserialize_ReturnObject()
    {
        //Arrange
        const string obj =
            "{\"test_a\":\"Test\",\"test_b\":2,\"test_c\":0.8,\"test_d\":true,\"test_e\":{\"test_a\":\"Test\"},\"test_f\":[\"A\",\"B\"]}";

        //Act
        var result = JsonHelper.Deserialize<JsonDocument>(obj);

        //Assert
        Assert.NotNull(result);
        Assert.Equal(JsonValueKind.Object, result.RootElement.ValueKind);
        Assert.Equal("Test", result.RootElement.GetProperty("test_a").GetString());
        Assert.Equal(2, result.RootElement.GetProperty("test_b").GetInt32());
        Assert.Equal(0.8, result.RootElement.GetProperty("test_c").GetDouble());
        Assert.True(result.RootElement.GetProperty("test_d").GetBoolean());
        Assert.Equal(JsonValueKind.Object, result.RootElement.GetProperty("test_e").ValueKind);
        Assert.Equal("Test", result.RootElement.GetProperty("test_e").GetProperty("test_a").GetString());
        Assert.Equal(JsonValueKind.Array, result.RootElement.GetProperty("test_f").ValueKind);
        Assert.Equal("A", result.RootElement.GetProperty("test_f")[0].GetString());
    }

    [Theory]
    [InlineData("")]
    [InlineData("[")]
    [InlineData(" ")]
    public void Deserialize_ThrowExceptionWhenInvalidString(string value)
    {
        Assert.Throws<JsonException>(() => JsonHelper.Deserialize<object?>(value));
    }

    #endregion

    #region EnvExampleBuilder

    private class FakeKey1 : Key
    {
        public FakeKey1() : base("FAKE_KEY_ONE", "1", ["This is a fake key 1"], "1.0.1")
        {
            RuleFor(x => x.Int).GreaterThan(0).LessThan(9);
        }
    }

    private class FakeKey2 : Key
    {
        public FakeKey2() : base("FAKE_KEY_TWO", "TEST", ["This is a fake key 2", "And key number 2 has another documentation"], "2.0.0")
        {
            RuleFor(x => x.String).NotEmpty().MaximumLength(15);
        }
    }

    [Fact]
    public void GetFileContent_ReturnsCorrectContentForUnixEndOfLine()
    {
        //Arrange
        const string expectedText = ""
                                    + "# Generated by EnvExampleBuilder\n\n"
                                    + "# Since version: 1.0.1\n"
                                    + "# Type: Int32\n"
                                    + "# This is a fake key 1\n"
                                    + "FAKE_KEY_ONE=\"1\"\n\n"
                                    + "# Since version: 2.0.0\n"
                                    + "# Type: String\n"
                                    + "# This is a fake key 2\n"
                                    + "# And key number 2 has another documentation\n"
                                    + "FAKE_KEY_TWO=\"TEST\"\n\n";

        //Act
        var envFileContent = EnvExampleBuilder.GetFileContent([typeof(FakeKey1), typeof(FakeKey2)], "\n");

        //Assert
        Assert.Equal(expectedText, envFileContent);
    }

    #endregion
}
